# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matthew/Source/cpp/InBloom/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matthew/Source/cpp/InBloom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/Source/cpp/InBloom/CMakeFiles /home/matthew/Source/cpp/InBloom/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/Source/cpp/InBloom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named InBloom

# Build rule for target.
InBloom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 InBloom
.PHONY : InBloom

# fast build rule for target.
InBloom/fast:
	$(MAKE) -f CMakeFiles/InBloom.dir/build.make CMakeFiles/InBloom.dir/build
.PHONY : InBloom/fast

#=============================================================================
# Target rules for targets named BloomFilter

# Build rule for target.
BloomFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BloomFilter
.PHONY : BloomFilter

# fast build rule for target.
BloomFilter/fast:
	$(MAKE) -f CMakeFiles/BloomFilter.dir/build.make CMakeFiles/BloomFilter.dir/build
.PHONY : BloomFilter/fast

BloomFilter.o: BloomFilter.cpp.o

.PHONY : BloomFilter.o

# target to build an object file
BloomFilter.cpp.o:
	$(MAKE) -f CMakeFiles/BloomFilter.dir/build.make CMakeFiles/BloomFilter.dir/BloomFilter.cpp.o
.PHONY : BloomFilter.cpp.o

BloomFilter.i: BloomFilter.cpp.i

.PHONY : BloomFilter.i

# target to preprocess a source file
BloomFilter.cpp.i:
	$(MAKE) -f CMakeFiles/BloomFilter.dir/build.make CMakeFiles/BloomFilter.dir/BloomFilter.cpp.i
.PHONY : BloomFilter.cpp.i

BloomFilter.s: BloomFilter.cpp.s

.PHONY : BloomFilter.s

# target to generate assembly for a file
BloomFilter.cpp.s:
	$(MAKE) -f CMakeFiles/BloomFilter.dir/build.make CMakeFiles/BloomFilter.dir/BloomFilter.cpp.s
.PHONY : BloomFilter.cpp.s

InBloom.o: InBloom.cpp.o

.PHONY : InBloom.o

# target to build an object file
InBloom.cpp.o:
	$(MAKE) -f CMakeFiles/InBloom.dir/build.make CMakeFiles/InBloom.dir/InBloom.cpp.o
.PHONY : InBloom.cpp.o

InBloom.i: InBloom.cpp.i

.PHONY : InBloom.i

# target to preprocess a source file
InBloom.cpp.i:
	$(MAKE) -f CMakeFiles/InBloom.dir/build.make CMakeFiles/InBloom.dir/InBloom.cpp.i
.PHONY : InBloom.cpp.i

InBloom.s: InBloom.cpp.s

.PHONY : InBloom.s

# target to generate assembly for a file
InBloom.cpp.s:
	$(MAKE) -f CMakeFiles/InBloom.dir/build.make CMakeFiles/InBloom.dir/InBloom.cpp.s
.PHONY : InBloom.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... InBloom"
	@echo "... rebuild_cache"
	@echo "... BloomFilter"
	@echo "... BloomFilter.o"
	@echo "... BloomFilter.i"
	@echo "... BloomFilter.s"
	@echo "... InBloom.o"
	@echo "... InBloom.i"
	@echo "... InBloom.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

